config/routes.rb
Rails.application.routes.draw do
  root :to => 'products#index'
  resources :products
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :name, :presence => true
  validates :cost, :presence => true
  validates :country, :presence => true
  validates :image, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
    render :index
  end
  def show
    @product = Product.find(params[:id])
    render :show
  end
  def new
    @product = Product.new
    render :new
  end
  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "Product successfully added!"
      redirect_to products_path
    else
      render :new
    end
  end
  def edit
    @product = Product.find(params[:id])
    render :edit
  end
  def update
    @product= Product.find(params[:id])
    if @product.update(product_params)
      redirect_to products_path
    else
      render :edit
    end
  end
  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end


private
  def product_params
    params.require(:product).permit(:name, :cost, :country, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
    <div class="nav-wrapper ">
      <a href="/" class="brand-logo center"> <%= image_tag("LOTG-Logo.gif", class: "resizeLogo") %> </a>
    </div>
  </nav>
    <div class="container">
          <%= yield %>
    </div>
  </body>
</html>

app/views/products/_form.html.erb
<%= render "layouts/errors", :object => @product %>

<%= form_for @product do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :cost %>
  <%= f.number_field :cost %>
  <%= f.label :country %>
  <%= f.text_field :country %>
  <%= f.label :image %>
  <%= f.text_field :image %>
  <%= f.submit  %>
<% end %>
<br><br>

app/views/products/edit.html.erb
<% content_for(:title, "Edit " + @product.name) %>

<h1>Edit product</h1>

<%= render "form" %>

app/views/products/index.html.erb
<% content_for(:title, "Home") %>
  <h5>Welcome to the Land of the Gummies Administator section. You can view each of your products in the display below. Click here to <a href="/products/new">create a new product</a>.</h5>

<h1 style="text-align: center;">Products</h1>
    <h4 style="text-align: center;"><%= flash[:notice] %></h4>  
<% if @products.any? %>
    <div class="row">

      <% @products.each do |product| %>
      <div class="col m4">
        <div class="card">
          <div class="card-image">
            <%= image_tag product.image, class: "thumbnails"%>
          </div>
          <div class="card-content center">
            <%= link_to product.name, product_path(product) %>
          </div>
        </div>
      </div>
  <% end %>
</ul>
<% else %>
  <p style="text-align: center;">You don't have any products listed yet!</p>
<% end %>

app/views/products/new.html.erb
<% content_for(:title, "New Product") %>
<h1>Register New Product</h1>

<%= render "form" %>

app/views/products/show.html.erb
<% content_for(:title, @product.name) %>

<div class="row">
  <div class="col m6">
    <div class="card">
      <div class="card-image">
        <%= image_tag @product.image, class: "resizeImg"%>

      </div>
      <div class="card-content center">
        <h3><%= @product.name %></h3>
        <h5>Cost per pound: $<%= @product.cost %> </h5>
        <h5>Country of Origin: <%= @product.country %> </h5>
      </div>
    </div>
  </div>
  <div class="col m6">
    <%= link_to image_tag("edit.png", id: "editImage"), edit_product_path(@product) %>
    <h2 style="text-align: center;"><%= link_to "Delete Record", product_path(@product),
                             :data => {:confirm => "You sure?",
                                       :method => "delete"} %></h2>

  </div>
</div>